const lessonTitle = "没有标准的答案";

const lessonData = [
    // 正文第 1 段
    ["讲台上", "jiǎng tái shàng", "on the podium", "di atas pentas / pentas guru"],
    ["，", "", "", ""],
    ["两鬓斑白的", "liǎng bìn bān bái de", "graying at the temples", "berambut putih di kedua-dua belah pelipis"],
    ["老师", "lǎo shī", "teacher", "cikgu / guru"],
    ["正在", "zhèng zài", "currently", "sedang"],
    ["摆弄着", "bǎi nòng zhe", "fiddling with / arranging", "mempermainkan / mengolak-alik / menyusun"],
    ["桌上的", "zhuō shàng de", "on the table's", "atas meja punya"],
    ["瓶瓶管管", "píng píng guǎn guǎn", "bottles and tubes", "botol-botol dan tabung-tabung uji"],
    ["，", "", "", ""],
    ["老师", "lǎo shī", "teacher", "guru itu"],
    ["早年", "zǎo nián", "in his early years", "pada tahun-tahun awal"],
    ["是", "shì", "was", "adalah"],
    ["留美归国", "liú měi guī guó", "returned to the country from studying in the US", "kembali ke tanah air selepas belajar di Amerika Syarikat"],
    ["学者", "xué zhě", "scholar", "sarjana / ahli akademik"],
    ["，", "", "", ""],
    ["退休", "tuì xiū", "retired", "bersara"],
    ["后", "hòu", "after", "selepas"],
    ["被", "bèi", "by (passive)", "di- / oleh"],
    ["学校", "xué xiào", "school", "pihak sekolah"],
    ["请来", "qǐng lái", "invited over", "jemput datang / diundang"],
    ["为我们", "wèi wǒ men", "for us", "untuk kami"],
    ["授课", "shòu kè", "teach / give lessons", "mengajar / memberi kuliah"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 2 段

    ["那是", "nà shì", "That was", "Itu adalah"],
    ["高中", "gāo zhōng", "senior high school", "sekolah menengah atas"],
    ["考试", "kǎo shì", "examination", "peperiksaan"],
    ["前的", "qián de", "before's", "sebelum punya"],
    ["最后一堂", "zuì hòu yì táng", "the very last (class)", "waktu pelajaran yang terakhir"],
    ["化学课", "huà xué kè", "chemistry class", "kelas kimia"],
    ["，", "", "", ""],
    ["同学们", "tóng xué men", "classmates", "murid-murid / rakan sekelas"],
    ["一个个", "yí gè gè", "one by one", "satu demi satu"],
    ["正襟危坐地", "zhèng jīn wéi zuò de", "sitting up straight and properly", "duduk tegak dengan bersopan santun / serius"],
    ["注视着", "zhù shì zhe", "gazing at / watching closely", "memperhatikan / merenung"],
    ["老师", "lǎo shī", "teacher", "cikgu"],
    ["给我们", "gěi wǒ men", "for us", "kepada kami"],
    ["做实验", "zuò shí yàn", "conduct an experiment", "menjalankan eksperimen"],
    ["。", "", "", ""],
    ["老师", "lǎo shī", "teacher", "Cikgu"],
    ["首先", "shǒu xiān", "firstly / first", "mula-mula / pertama sekali"],
    ["拿出一瓶", "ná chū yì píng", "took out a bottle of", "mengeluarkan sebotol"],
    ["纯净水", "chún jìng shuǐ", "pure water", "air tulen / air suling"],
    ["，", "", "", ""],
    ["倒进", "dào jìn", "poured into", "menuangkan ke dalam"],
    ["烧杯", "shāo bēi", "beaker", "bikar"],
    ["里", "lǐ", "inside", "dalam"],
    ["。", "", "", ""],
    ["点燃", "diǎn rán", "ignited / lit", "menyalakan"],
    ["酒精灯", "jiǔ jīng dēng", "alcohol burner / lamp", "lampu alkohol"],
    ["，", "", "", ""],
    ["要在", "yào zài", "under / if it were in (the past)", "sekiranya pada waktu / biasanya pada"],
    ["往日", "wǎng rì", "former days / past days", "hari-hari yang lalu"],
    ["，", "", "", ""],
    ["老师", "lǎo shī", "teacher", "cikgu"],
    ["肯定", "kěn dìng", "definitely / surely", "pasti akan"],
    ["会", "huì", "will", "akan"],
    ["趁", "chèn", "take advantage of (before water boils)", "sementara / mengambil kesempatan sebelum"],
    ["水沸腾", "shuǐ fèi téng", "water boils", "air mendidih"],
    ["前", "qián", "before", "sebelum"],
    ["给我们", "gěi wǒ men", "for us", "kepada kami"],
    ["讲解", "jiǎng jiě", "explain", "menerangkan / menjelaskan"],
    ["实验的", "shí yàn de", "experiment's", "eksperimen punya"],
    ["过程", "shí yàn de guò chéng", "process", "proses"],
    ["和", "hé", "and", "dan"],
    ["目的", "mù dì", "purpose / objective", "tujuan"],
    ["，", "", "", ""],
    ["然而", "rán ér", "however / yet", "namun / bagaimanapun"],
    ["，", "", "", ""],
    ["那一次", "nà yí cì", "that particular time", "kali itu"],
    ["老师", "lǎo shī", "teacher", "cikgu"],
    ["什么", "shén me", "anything", "apa-apa pun"],
    ["话", "huà", "words", "perkataan / cakap"],
    ["都", "dōu", "all", "langsung"],
    ["没说", "méi shuō", "did not say", "tidak berkata"],
    ["，", "", "", ""],
    ["只是", "zhǐ shì", "just / merely", "hanya / sekadar"],
    ["静静地", "jìng jìng de", "quietly / silently", "dengan senyap / tenang"],
    ["等", "děng", "wait for", "menunggu"],
    ["水沸腾", "shuǐ fèi téng", "water boils / boiling", "air mendidih"],
    ["起来", "qǐ lái", "up", "semula"],
    ["，", "", "", ""],
    ["然后", "rán hòu", "then", "kemudian"],
    ["从", "cóng", "from", "dari / daripada"],
    ["那一排", "nà yì pái", "that row of", "barisan itu"],
    ["试管", "shì guǎn", "test tubes", "tabung uji"],
    ["中", "zhōng", "among / in", "dalam"],
    ["抽取", "chōu qǔ", "extract / draw out", "mengambil / mengeluarkan"],
    ["一支", "yì zhī", "one (measure word for tube)", "sebatang"],
    ["试管", "shì guǎn", "test tube", "tabung uji"],
    ["，", "", "", ""],
    ["把", "bǎ", "structural particle", ""],
    ["管里", "guǎn lǐ", "inside the tube", "dalam tabung uji"],
    ["一些", "yì xiē", "some", "sedikit"],
    ["黑色的", "hēi sè de", "black", "berwarna hitam"],
    ["颗粒", "kē lì", "granules / particles", "butiran / bijian kecil"],
    ["倒进", "dào jìn", "poured into", "menuangkan ke dalam"],
    ["沸水", "fèi shuǐ", "boiling water", "air mendidih"],
    ["里", "lǐ", "inside", "dalam"],
    ["，", "", "", ""],
    ["原本", "yuán běn", "originally", "asalnya / pada mulanya"],
    ["清澈的", "qīng chè de", "clear / limpid", "jernih / lut sinar"],
    ["水", "shuǐ", "water", "air"],
    ["一下子", "yí xià zi", "all of a sudden / instantly", "dalam sekelip mata"],
    ["变成了", "biàn chéng le", "turned into / became", "bertukar menjadi"],
    ["黑色", "hēi sè", "black", "hitam"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 3 段

    ["同学们", "tóng xué men", "Classmates", "Murid-murid"],
    ["你看我", "nǐ kàn wǒ", "you look at me", "kamu tengok saya"],
    ["，", "", "", ""],
    ["我看你", "wǒ kàn nǐ", "I look at you", "saya tengok kamu"],
    ["，", "", "", ""],
    ["不明白", "bù míng bai", "did not understand", "tidak faham"],
    ["老师", "lǎo shī", "teacher", "cikgu"],
    ["这是", "zhè shì", "this is", "ini adalah"],
    ["在", "zài", "doing (aspect)", "sedang"],
    ["做什么", "zuò shén me", "doing what", "melakukan apa"],
    ["处理", "", "", ""],
    ["，", "", "", ""],
    ["最起码", "zuì qǐ mǎ", "at the very least", "sekurang-kurangnya"],
    ["老师", "lǎo shī", "teacher", "cikgu"],
    ["应该", "yīng gāi", "should / ought to", "sepatutnya / harus"],
    ["告诉", "gào su", "tell", "memberitahu"],
    ["我们", "wǒ men", "us", "kami"],
    ["那些", "nà xiē", "those", "itu / yang itu"],
    ["黑色", "hēi sè", "black", "hitam punya"],
    ["颗粒", "kē lì", "granules", "butiran"],
    ["是", "shì", "were", "adalah"],
    ["什么", "shén me", "what", "apa"],
    ["东西", "dōng xi", "thing / substance", "benda / bahan"],
    ["啊", "ā", "particle", "lah"],
    ["结构", "", "", ""],
    ["布局", "", "", ""],
    ["。", "", "", ""],
    ["但", "dàn", "but", "Namun / tetapi"],
    ["老师", "lǎo shī", "teacher", "cikgu"],
    ["不说", "bù shuō", "did not speak", "tidak cakap / membisu"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kami"],
    ["也", "yě", "also", "pun"],
    ["不好", "bù hǎo", "not appropriate to", "tidak manis / tidak sesuai"],
    ["多问", "duō wèn", "ask further / ask more", "tanya lebih-lebih"],
    ["。", "", "", ""],
    ["只是", "zhǐ shì", "just / only", "hanya / sekadar"],
    ["一个个", "yí gè gè", "one by one", "masing-masing"],
    ["静静地", "jìng jìng de", "quietly", "dengan senyap"],
    ["看着", "kàn zhe", "watching", "menyaksikan / melihat"],
    ["老师", "lǎo shī", "teacher", "cikgu"],
    ["往", "wǎng", "into / towards", "ke dalam"],
    ["沸水中", "fèi shuǐ zhōng", "boiling water", "dalam air mendidih"],
    ["倒入", "dào rù", "pour into", "memasukkan / menuangkan"],
    ["一些", "yì xiē", "some", "sedikit"],
    ["白色的", "bái sè de", "white", "berwarna putih"],
    ["颗粒", "kē lì", "granules", "butiran"],
    ["，", "", "", ""],
    ["再", "zài", "then / furthermore", "kemudian / lalu"],
    ["倒入", "dào rù", "pour into", "menuangkan"],
    ["一些", "yì xiē", "some", "sedikit"],
    ["白色的", "bái sè de", "white", "putih punya"],
    ["粉末", "fěn mò", "powder", "serbuk"],
    ["，", "", "", ""],
    ["黑色的", "hēi sè de", "black", "hitam punya"],
    ["水", "shuǐ", "water", "air"],
    ["一眨眼", "yì zhǎ yǎn", "in the blink of an eye", "dalam sekelip mata"],
    ["变成了", "biàn chéng le", "turned into", "bertukar menjadi"],
    ["咖啡色", "kā fēi sè", "coffee color / brown", "warna kopi / coklat"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 4 段

    ["随后", "suí hòu", "Subsequently / right after", "Sejurus selepas itu"],
    ["老师", "lǎo shī", "teacher", "cikgu"],
    ["停了", "tíng le", "stopped", "berhenti"],
    ["下来", "xià lái", "down", "semula"],
    ["，", "", "", ""],
    ["扫视", "sǎo shì", "scanned / glanced around", "memandang keliling / menatap"],
    ["我们", "wǒ men", "us", "kami"],
    ["一眼", "yì yǎn", "a glance", "sekilas"],
    ["，", "", "", ""],
    ["然后", "rán hòu", "then", "kemudian"],
    ["微笑着", "wēi xiào zhe", "smilingly", "sambil tersenyum"],
    ["说", "shuō", "said", "dan berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["好了", "hǎo le", "Alright / OK", "Baiklah"],
    ["处理", "", "", ""],
    ["，", "", "", ""],
    ["现在", "xiàn zài", "now", "sekarang"],
    ["有", "yǒu", "is there", "ada"],
    ["哪位", "nǎ wèi", "which (person)", "sesiapa / mana-mana seorang"],
    ["同学", "tóng xué", "student", "murid / pelajar"],
    ["可以", "kě yǐ", "can", "boleh"],
    ["告诉我", "gào su wǒ", "tell me", "memberitahu saya"],
    ["，", "", "", ""],
    ["这", "zhè", "this", "ini"],
    ["烧杯里的", "shāo bēi lǐ de", "inside the beaker's", "dalam bikar punya"],
    ["东西", "dōng xi", "substance / thing", "benda / bahan"],
    ["是", "shì", "is", "adalah"],
    ["什么", "shén me", "what", "apa"],
    ["？", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 5 段

    ["这", "zhè", "This", "Perkara ini"],
    ["我们", "wǒ men", "we", "kami"],
    ["哪会", "nǎ huì", "how could we (rhetorical)", "bagaimana mungkin / mana tahu"],
    ["知道", "zhī dào", "know", "tahu"],
    ["，", "", "", ""],
    ["一个个", "yí gè gè", "each one", "masing-masing / semua sekali"],
    ["直摇头", "zhí yáo tóu", "kept shaking heads", "asyik menggelengkan kepala"],
    ["，", "", "", ""],
    ["老师", "lǎo shī", "teacher", "cikgu"],
    ["狡黠地", "jiǎo xiá de", "cunningly / mischievously / slyly", "dengan licik / penuh tipu helah yang lucu / cerdik"],
    ["笑着", "xiào zhe", "smiling", "tersenyum"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["那么", "nà me", "then", "Kalau begitu"],
    ["有谁", "yǒu shéi", "is there anyone who", "adakah sesiapa"],
    ["愿意", "yuàn yì", "willing to", "sudi / rela"],
    ["上来", "shàng lái", "come up", "naik ke depan"],
    ["尝一尝", "cháng yì cháng", "have a taste of", "rasa sedikit / mencicipi"],
    ["它的", "tā de", "its", "ia punya"],
    ["味道", "wèi dào", "taste / flavor", "rasa"],
    ["？", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 6 段

    ["同学们", "tóng xué men", "Classmates", "Murid-murid"],
    ["被", "bèi", "by (passive particle)", "telah di- / oleh"],
    ["老师的", "lǎo shī de", "teacher's", "cikgu punya"],
    ["这个", "zhè ge", "this", "ini punya"],
    ["提议", "tí yì", "proposal / suggestion", "cadangan / pelawaan"],
    ["给", "gěi", "structural particle", ""],
    ["吓呆了", "xià dāi le", "dumbfounded by fear / stunned", "terperanjat / tergamam ketakutan"],
    ["，", "", "", ""],
    ["一个个", "yí gè gè", "one by one", "masing-masing"],
    ["瞠目结舌", "chēng mù jié shé", "staring tongue-tied / dumbstruck", "terperangah dengan mata terbeliak dan lidah terkelu"],
    ["，", "", "", ""],
    ["满脸", "mǎn liǎn", "full of face / covered with", "seluruh muka penuh dengan"],
    ["困惑", "kùn huò", "confusion / perplexity", "kehairanan / kekeliruan"],
    ["，", "", "", ""],
    ["要知道", "yào zhī dào", "must bear in mind / you know", "perlu tahu / harus diingat"],
    ["这", "zhè", "this", "ini"],
    ["可是", "kě shì", "exactly is / after all", "memang / adalah"],
    ["化学", "huà xué", "chemistry", "kimia"],
    ["实验课", "shí yàn kè", "laboratory / experiment class", "kelas amali / eksperimen"],
    ["哩", "li", "modal particle", "lah"],
    ["设计", "", "", ""],
    ["结构", "", "", ""],
    ["。", "", "", ""],
    ["平时里", "píng shí lǐ", "usually / on ordinary days", "biasanya / pada hari biasa"],
    ["我们", "wǒ men", "we", "kami"],
    ["对", "duì", "towards", "terhadap / kepada"],
    ["烧杯里", "shāo bēi lǐ", "inside the beaker", "dalam bikar"],
    ["那些", "nà xiē", "those", "bahan-bahan itu"],
    ["物质", "wù zhì", "substances / matter", "bahan / jirim"],
    ["一个个", "yí gè gè", "each and every one", "semuanya sekali"],
    ["小心谨慎", "xiǎo xīn jǐn shèn", "extremely cautious / careful", "sangat berhati-hati / berwaspada"],
    ["处理", "", "", ""],
    ["，", "", "", ""],
    ["生怕", "shēng pà", "for fear that / lest", "bimbang kalau-kalau / takut sangat"],
    ["一不留心", "yì bù liú xīn", "a moment of carelessness", "terleka seketika / kurang berhati-hati"],
    ["被", "bèi", "by (passive)", "di-"],
    ["烧杯里的", "shāo bēi lǐ de", "inside beaker's", "dalam bikar punya"],
    ["那些", "nà xiē", "those", "bahan itu"],
    ["硫酸", "liú suān", "sulfuric acid", "asid sulfurik"],
    ["、", "", "", ""],
    ["硝酸", "xiāo suān", "nitric acid", "asid nitrik"],
    ["什么的", "shén me de", "and such / etc.", "dan seumpamanya"],
    ["伤害", "shāng hài", "harm / hurt", "mencederakan / memudaratkan"],
    ["，", "", "", ""],
    ["哪敢", "nǎ gǎn", "how dare we (rhetorical)", "mana berani / tidak berani langsung"],
    ["去", "qù", "go to", "untuk pergi"],
    ["品尝", "pǐn cháng", "taste", "merasa / mencicipi"],
    ["？", "", "", ""],
    ["也亏", "yě kuī", "thanks to (sarcastic / surprisingly he could)", "sampai hati pula / nasib baiklah (sinis)"],
    ["老师", "lǎo shī", "teacher", "cikgu"],
    ["他老人家", "tā lǎo rén jiā", "his old self (respectful)", "beliau yang sudah tua itu"],
    ["想得出来", "xiǎng de chū lái", "could think of this", "boleh terfikir jalan begini"],
    ["，", "", "", ""],
    ["要我们", "yào wǒ men", "ask us to", "meminta kami"],
    ["去品尝", "qù pǐn cháng", "go to taste", "pergi merasa"],
    ["这", "zhè", "this", "ini"],
    ["烧杯里的", "shāo bēi lǐ de", "inside beaker's", "dalam bikar punya"],
    ["东西", "dōng xi", "substance", "benda"],
    ["，", "", "", ""],
    ["你说", "nǐ shuō", "you say", "kamu cakaplah"],
    ["我们", "wǒ men", "we", "kami"],
    ["能不害怕", "néng bú hài pà", "could we not be scared (rhetorical)", "bolehkah tidak takut / tentulah takut"],
    ["吗", "ma", "particle", "kah"],
    ["？", "", "", ""],

    ["\n", "", "", ""], // 👈 第 7 段

    ["也不知", "yě bù zhī", "Also do not know", "Entah / tidak tahu juga"],
    ["过了多久", "guò le jiǔ", "how long passed", "berapa lama telah berlalu"],
    ["处理", "", "", ""],
    ["，", "", "", ""],
    ["只见", "zhǐ jiàn", "only saw", "hanya kelihatan"],
    ["坐在", "zuò zài", "sitting in", "duduk di"],
    ["我前面的", "wǒ qián mian de", "in front of me's", "depan saya punya"],
    ["班长", "bān zhǎng", "class monitor", "ketua kelas"],
    ["站起身来", "zhàn qǐ shēn lái", "stood up", "bangun berdiri"],
    ["设计", "", "", ""],
    ["结构", "", "", ""],
    ["。", "", "", ""],
    ["在", "zài", "under / during", "Dalam keadaan / ketika"],
    ["同学们", "tóng xué men", "classmates'", "murid-murid punya"],
    ["惊讶的", "jīng yà de", "surprised / astonished", "yang terkejut / hairan"],
    ["注视中", "zhù shì zhōng", "gaze / watching", "pandangan mata"],
    ["挪到", "nuó dào", "moved slowly to / budged to", "melangkah perlahan ke"],
    ["讲台上", "jiǎng tái shàng", "podium", "atas pentas guru"],
    ["，", "", "", ""],
    ["勇敢", "yǒng gǎn", "bravely", "dengan berani"],
    ["而", "ér", "and", "dan"],
    ["悲壮地", "bēi zhuàng de", "solemnly and tragically", "penuh wira / berani mati"],
    ["端起", "duān qǐ", "held up (beaker with both hands)", "mengangkat up / menatang"],
    ["烧杯", "shāo bēi", "beaker", "bikar itu"],
    ["慢慢地", "màn màn de", "slowly", "perlahan-lahan"],
    ["抿了", "mǐn le", "sipped", "mencicipi / menghirup sedikit"],
    ["一口", "yì kǒu", "a mouthful / a sip", "seteguk / sikit"],
    ["，", "", "", ""],
    ["轻轻", "qīng qīng", "gently (contextual for original implementation layout)", "perlahan-lahan"],
    ["地", "de", "particle", ""],
    ["在", "zài", "in (contextual layout sync)", "di"],
    ["心中", "xīn zhōng", "mind", "dalam hati"],
    ["动着", "dòng zhe", "moving", "menggerakkan"],
    ["嘴唇", "zuǐ chún", "lips", "bibir"],
    ["；", "", "", ""],
    ["然后", "rán hòu", "then", "kemudian / selepas itu"],
    ["只听得", "zhǐ tīng de", "only heard", "hanya terdengar"],
    ["班长的", "bān zhǎng de", "class monitor's", "ketua kelas punya"],
    ["一声", "yì shēng", "a sound of", "satu"],
    ["惊呼", "jīng hū", "exclamation / cry of surprise", "jeritan terkejut / laungan"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["这是", "zhè shì", "This is", "Ini adalah"],
    ["咖啡", "kā fēi", "coffee", "kopi"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 8 段

    ["什么", "shén me", "What", "Apa"],
    ["？", "", "", ""],
    ["教室里", "jiào shì lǐ", "Inside the classroom", "Dalam bilik darjah"],
    ["顿时", "dùn shí", "instantly / straightaway", "serta-merta / serta menteri"],
    ["炸开了锅", "zhà kāi le guō", "exploded like a pot / chaotic with noise", "menjadi riuh-rendah / binggit / gempar"],
    ["，", "", "", ""],
    ["我说", "wǒ shuō", "I said (thought to myself)", "patutlah saya fikir / saya berkata"],
    ["老师的", "lǎo shī de", "teacher's", "cikgu punya"],
    ["操作", "cāo zuò", "operation / steps", "cara kerja / pengendalian"],
    ["怎么", "zěn me", "why / how come", "mengapa"],
    ["有种", "yǒu zhǒng", "had a kind of", "mempunyai sejenis"],
    ["似曾相识的", "sì céng xiāng shí de", "seemingly familiar / deja vu", "perasaan yang pernah dilihat / biasa nampak"],
    ["感觉", "gǎn jué", "feeling", "perasaan"],
    ["呢", "ne", "particle", "ya"],
    ["！", "", "", ""],
    ["原来", "yuán lái", "It turned out that", "Rupa-rupanya"],
    ["那黑色的", "nà hēi sè de", "that black", "hitam punya itu"],
    ["颗粒", "kē lì", "granules", "butiran"],
    ["是", "shì", "were", "adalah"],
    ["咖啡粉粒", "kā fēi fěn lì", "coffee powder granules", "butiran serbuk kopi"],
    ["啊", "ā", "particle", "lah"],
    ["，", "", "", ""],
    ["而", "ér", "and", "manakala / dan"],
    ["那白色的", "nà bái sè de", "that white", "putih punya itu"],
    ["颗粒", "kē lì", "granules", "butiran"],
    ["自然", "zì rán", "naturally", "semestinya / sudah tentu"],
    ["是", "shì", "was", "adalah"],
    ["糖", "táng", "sugar", "gula"],
    ["，", "", "", ""],
    ["白色的", "bái sè de", "white", "putih punya"],
    ["粉末", "fěn mò", "powder", "serbuk"],
    ["不用说", "bú yòng shuō", "needless to say", "tidak payah cakap lagi / sudah tentu"],
    ["就是", "jiù shì", "exactly was", "adalah"],
    ["咖啡", "kā fēi", "coffee", "kopi"],
    ["奶精", "nǎi jīng", "creamer", "krimer / seri susu"],
    ["了", "le", "particle", ""],
    ["设计", "", "", ""],
    ["结构", "", "", ""],
    ["。", "", "", ""],
    ["我们", "wǒ men", "We", "Kami"],
    ["怎么也", "zěn me yě", "by no means / never", "bagaimanapun langsung tidak"],
    ["没想到", "méi xiǎng dào", "did not expect", "menyangka / mengira"],
    ["一贯", "yí guàn", "consistently / always", "sentiasa / yang selama ini"],
    ["严谨的", "yán jǐn de", "rigorous / strict", "teliti / ketat / berdisiplin"],
    ["老师", "lǎo shī", "teacher", "cikgu"],
    ["，", "", "", ""],
    ["竟然", "jìng rán", "unexpectedly", "rupa-rupanya / sampai hati"],
    ["在这", "zài zhè", "in this", "dalam ini"],
    ["最后一堂", "zuì hòu yì táng", "last lesson", "waktu pelajaran terakhir"],
    ["课上", "kè shàng", "class", "punya kelas"],
    ["给我们", "gěi wǒ men", "for us", "kepada kami"],
    ["开了个", "kāi le gè", "played a (joke)", "membuat satu"],
    ["不大不小的", "bú dà bù xiǎo de", "neither big nor small / moderate", "agak besar / gurauan sederhana"],
    ["玩笑", "wán xiào", "joke", "gurauan"],
    ["处理", "", "", ""],
    ["，", "", "", ""],
    ["一本正经地", "yī běn zhèng jīng de", "solemnly / in all seriousness", "dengan penuh serius / bersungguh-sungguh"],
    ["给我们", "gěi wǒ men", "for us", "untuk kami"],
    ["煮了", "zhǔ le", "boiled / brewed", "memasak / membancuh"],
    ["一回", "yì huí", "one time", "sekali"],
    ["咖啡", "kā fēi", "coffee", "kopi"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 第 9 段

    ["我们", "wǒ men", "We", "Kami"],
    ["纷纷", "fēn fēn", "one after another", "bertubi-tubi / bertumpu-tumpu"],
    ["问", "wèn", "asked", "bertanya kepada"],
    ["老师", "lǎo shī", "teacher", "cikgu"],
    ["，", "", "", ""],
    ["上这堂课的", "shàng zhè táng kè de", "conducting this lesson's", "menghadiri kelas ini punya"],
    ["目的是", "mù dì shì", "purpose is", "tujuan adalah"],
    ["什么", "shén me", "what", "apa"],
    ["，", "", "", ""],
    ["答案", "dá àn", "answer", "jawapan"],
    ["又是什么", "yòu shì shén me", "again is what", "pula adalah apa"],
    ["，", "", "", ""],
    ["老师", "lǎo shī", "teacher", "cikgu"],
    ["摇摇头", "yáo tóu yáo tóu", "shook head", "menggelengkan kepala"],
    ["，", "", "", ""],
    ["慈祥地", "cí xiáng de", "kindly / amiably", "dengan penuh kasih sayang / bapa"],
    ["看着", "kàn zhe", "watching", "melihat"],
    ["我们", "wǒ men", "us", "kami"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["这样做的", "zhè yàng zuò de", "doing this's", "berbuat begini punya"],
    ["目的是", "mù dì shì", "purpose is", "tujuan adalah"],
    ["想给", "xiǎng gěi", "want to give", "mahu memberi"],
    ["同学们", "tóng xué men", "classmates", "murid-murid"],
    ["一些", "yì xiē", "some", "sedikit"],
    ["生活的", "shēng huó de", "life's", "kehidupan punya"],
    ["启示", "qǐ shì", "enlightenment / inspiration / revelation", "pengajaran / iktibar / petunjuk"],
    ["，", "", "", ""],
    ["那就是", "nà jiù shì", "that is", "iaitu"],
    ["事物", "shì wù", "things / matters", "perkara / sesuatu benda"],
    ["是", "shì", "is", "adalah"],
    ["变化着的", "biàn huà zhē de", "changing", "sentiasa berubah / dinamik"],
    ["，", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["没有", "méi yǒu", "does not have", "tidak mempunyai"],
    ["标准答案", "biāo zhǔn dá àn", "standard answer", "jawapan standard / skema jawapan"],
    ["设计", "", "", ""],
    ["结构", "", "", ""],
    ["。", "", "", ""],
    ["我相信", "wǒ xiāng xìn", "I believe", "Saya percaya"],
    ["你们", "nǐ men", "you all", "kamu semua"],
    ["总有一天", "zǒng yǒu yì tiān", "will eventually one day", "akan ada suatu hari nanti"],
    ["会", "huì", "will", "akan"],
    ["领悟到", "lǐng wù dào", "comprehend / realize", "memahami / menghayati"],
    ["这其中的", "zhè qí zhōng de", "within this's", "di dalam ini punya"],
    ["意味", "yì wèi", "meaning / significance / flavor", "maksud / erti / kemanisan"],
    ["。", "", "", ""],
    ["好了", "hǎo le", "Alright", "Baiklah"],
    ["，", "", "", ""],
    ["今天的", "jīn tiān de", "today's", "hari ini punya"],
    ["课", "kè", "class", "kelas"],
    ["就", "jiù", "just", "pun"],
    ["到此为止", "dào cǐ wéi zhǐ", "stop here / conclude here", "sampai di sini sahaja"],
    ["处理", "", "", ""],
    ["，", "", "", ""],
    ["祝", "zhù", "wish", "mendoakan / mengucapkan"],
    ["同学们", "tóng xué men", "classmates", "murid-murid"],
    ["前程远大", "qián chéng yuǎn dà", "have a brilliant / great future", "masa depan yang cerah / gilang-gemilang"],
    ["，", "", "", ""],
    ["下课", "xià kè", "class is dismissed", "bersurai / tamat kelas"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 10 段

    ["十多年", "shí duō nián", "Ten odd years", "Sepuluh tahun lebih"],
    ["过去了", "guò qù le", "passed by", "telah berlalu"],
    ["设计", "", "", ""],
    ["结构", "", "", ""],
    ["。", "", "", ""],
    ["我已", "wǒ yǐ", "I have already", "Saya sudah pun"],
    ["从", "cóng", "from", "daripada / dari"],
    ["少年", "shào nián", "juvenile / youth", "remaja / budak kecil"],
    ["走向", "zǒu xiàng", "walked into / towards", "melangkah menuju ke"],
    ["青年", "qīng nián", "youth / young adult", "alam belia / pemuda"],
    ["、", "", "", ""],
    ["从", "cóng", "from", "daripada"],
    ["懵懂无知", "měng dǒng wú zhī", "ignorant and muddled / naive", "keadaan jahil dan tidak tahu apa-apa / mentah"],
    ["走向", "zǒu xiàng", "towards", "menuju ke"],
    ["成熟明理", "chéng shú míng lǐ", "mature and sensible", "matang dan bijaksana / memahami rasional"],
    ["，", "", "", ""],
    ["慢慢地", "màn màn de", "gradually / slowly", "perlahan-lahan"],
    ["体会了", "tǐ huì le", "understood / realized", "menghayati / memahami"],
    ["老师", "lǎo shī", "teacher's", "cikgu punya"],
    ["当初的", "dāng chū de", "original / initial", "pada asal usulnya / dahulu punya"],
    ["用意", "yòng yì", "intention", "maksud / niat"],
    ["结构", "", "", ""],
    ["布局", "", "", ""],
    ["。", "", "", ""],
    ["生活", "shēng huó", "Life", "Kehidupan / hidup"],
    ["就像是", "jiù xiàng shì", "just resembles a", "bagaikan / adalah seperti"],
    ["一杯", "yì bēi", "a cup of", "secawan"],
    ["纯净水", "chún jìng shuǐ", "pure water", "air tulen"],
    ["，", "", "", ""],
    ["无色", "wú sè", "colorless", "tanpa warna"],
    ["而", "ér", "and", "dan"],
    ["无味", "wú wèi", "flavorless", "tawar / tanpa rasa"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "namun / tetapi"],
    ["要想", "xiǎng yào", "if want to", "sekiranya mahu"],
    ["变成", "biàn chéng", "turn into", "menjadi"],
    ["一杯", "yì bēi", "a cup of", "secawan"],
    ["滴滴", "dī dī", "every drop of", "setiap titis"],
    ["香浓的", "xiāng nóng de", "rich and aromatic", "yang harum dan pekat / lazat"],
    ["咖啡", "kā fēi", "coffee", "kopi"],
    ["，", "", "", ""],
    ["就得", "jiù děi", "must then", "perlulah / haruslah"],
    ["不时", "bù shí", "from time to time", "sentiasa / dari masa ke masa"],
    ["加入", "jiā rù", "add into", "memasukkan"],
    ["勤劳", "qín láo", "diligence / hard work", "kerajinan / usaha gigih"],
    ["、", "", "", ""],
    ["汗水", "hàn shuǐ", "sweat", "air peluh"],
    ["、", "", "", ""],
    ["阳光", "yáng guāng", "sunshine", "cahaya matahari"],
    ["、", "", "", ""],
    ["雨露", "yǔ lù", "rain and dew", "titisan hujan dan embun"],
    ["和", "hé", "and", "dan"],
    ["真诚", "zhēn chéng", "sincerity", "keikhlasan"],
    ["，", "", "", ""],
    ["这样的", "zhè yàng de", "such a", "sebegini punya"],
    ["生活", "shēng huó", "life", "kehidupan"],
    ["才会", "cái huì", "only then will", "barulah akan"],
    ["变得", "biàn de", "become", "menjadi"],
    ["有滋有味", "yǒu zī yǒu wèi", "flavorful / interesting / delicious", "berwarna-warni / sangat menarik / sedap berseri"],
    ["起来", "qǐ lái", "up", "semula"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 11 段

    ["当年", "dāng nián", "In those years / back then", "Pada tahun itu / dahulu"],
    ["勇敢地", "yǒng gǎn de", "bravely", "dengan berani"],
    ["端起", "duān qǐ", "held up", "menatang / mengangkat up"],
    ["烧杯的", "shāo bēi de", "beaker's", "bikar punya"],
    ["班长", "bān zhǎng", "class monitor", "ketua kelas"],
    ["，", "", "", ""],
    ["现在", "xiàn zài", "now", "sekarang"],
    ["已是", "yǐ shì", "is already", "sudah pun menjadi"],
    ["耶鲁大学", "yē lǔ dà xué", "Yale University", "Universiti Yale"],
    ["最年轻的", "zuì nián qīng de", "the youngest", "paling muda punya"],
    ["访问学者", "fǎng wèn xué zhě", "visiting scholar", "sarjana pelawat / pakar akademik jemputan"],
    ["。", "", "", ""],
    ["电话里", "diàn huà lǐ", "Over the phone", "Dalam talian telefon"],
    ["和他", "hé tā", "with him", "dengan dia"],
    ["谈起", "tán qǐ", "talked about / chat about", "berbual tentang"],
    ["对生活的", "duì shēng huó de", "towards life's", "terhadap kehidupan punya"],
    ["这些", "zhè xiē", "these", "semua ini"],
    ["感悟", "gǎn wù", "insights / reflections", "penghayatan / kesedaran"],
    ["。", "", "", ""],
    ["他", "tā", "he", "Dia"],
    ["连连称是", "lián lián chēng shì", "nodded and agreed repeatedly", "bertubi-tubi mengiyakan / bersetuju sepenuhnya"],
    ["，", "", "", ""],
    ["只是", "zhǐ shì", "just / only", "cuma / hanya"],
    ["末了", "mò liǎo", "at the very end / finally", "pada akhirnya / akhir kata"],
    ["，", "", "", ""],
    ["电话", "diàn huà", "telephone", "telefon"],
    ["那端的", "nà duān de", "on the other end's", "sana punya bahagian"],
    ["他", "tā", "he", "dia"],
    ["轻轻地", "qīng qing de", "gently / softly", "dengan perlahan / lembut"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["还有", "hái yǒu", "still have", "Masih ada"],
    ["一点", "yì diǎn", "one point", "satu perkara lagi"],
    ["我想", "wǒ xiǎng", "I want to", "saya mahu"],
    ["补充", "bǔ chōng", "supplement / add on", "menambah / membuat ulasan tambahan"],
    ["一下", "yí xià", "a bit", "sedikit"],
    ["：", "", "", ""],
    ["那就是", "nà jiù _", "that is", "iaitu"],
    ["千万不要", "qiān wàn bú yào", "must never / by all means do not", "jangan sekali-kali / seboleh-bolehnya jangan"],
    ["被生活中", "bèi shēng huó zhōng", "by life's in", "oleh dalam kehidupan punya"],
    ["一些", "yì xiē", "some", "beberapa"],
    ["表面的", "biǎo miàn de", "superficial / surface", "luaran / kosmetik"],
    ["现象", "xiàn xiàng", "phenomena / appearance", "fenomena / rupa luaran"],
    ["所", "suǒ", "particle", ""],
    ["蒙蔽了", "méng bì le", "blinded / deceived", "diperdayakan / dikaburi"],
    ["，", "", "", ""],
    ["一个", "yí gè", "a / an", "seorang"],
    ["勇于", "yǒng yú", "have the courage to", "yang berani untuk"],
    ["尝试的", "cháng shì de", "try / attempt", "mencuba"],
    ["人", "rén", "person", "manusia"],
    ["，", "", "", ""],
    ["生活", "shēng huó", "life", "kehidupan"],
    ["总会", "zǒng huì", "always will", "pasti akan"],
    ["给他", "gěi tā", "give him", "memberinya"],
    ["一些", "yì xiē", "some", "sedikit"],
    ["意想不到的", "yì xiǎng bú dào de", "unexpected", "yang tidak disangka-sangka"],
    ["惊喜", "jīng xǐ", "pleasant surprises", "kejutan yang menggembirakan"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 文末出处

    ["（", "", "", ""],
    ["罗为辉", "luó wéi huī", "Luo Weihui (Author)", "Luo Weihui (Penulis)"],
    ["《", "", "", ""],
    ["没有标准的答案", "méi yǒu biāo zhǔn de dá àn", "There is No Standard Answer", "Tiada Skema Jawapan"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
